apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-api-dev
  namespace: argocd
spec:
  project: interview-project

  source:
    repoURL: https://github.com/Uttam963/devops-interview-gitops.git
    targetRevision: main
    path: charts/devops-api

    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true

    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m