replicaCount: 2

image:
  repository: ghcr.io/uttam963/devops-interview-api
  pullPolicy: IfNotPresent
  tag: "63b35fb9b9d5032c26ef8e1309ea329937565c8a"

application:
  environment: development
  version: v2-dev

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

serviceAccount:
  create: true
  name: devops-api

workloadIdentity:
  enabled: false
  clientId: ""